# infra/ansible/requirements.yml
collections:
  - name: kubernetes.core          # modules k8s, k8s_info, …
    version: ">=3.0.0,<4.0.0"      # dernière branche stable

  - name: community.kubernetes     # alias (kubeauth, etc.)
    version: ">=4.0.0,<5.0.0"

  - name: community.grafana
    version: ">=1.5.0,<2.0.0"

  - name: community.general        # helm, httpd, etc.
    version: ">=8.0.0,<9.0.0"
