apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devopstrack-rules
  namespace: monitoring
spec:
  groups:
    - name: devopstrack.rules
      rules:
        - alert: HighPodRestart
          expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Pod restart rate >0 ({{ $labels.namespace }}/{{ $labels.pod }})"
            description: "Container restarts >0 per 5 min."
