---
- name: Provision monitoring stack
  hosts: cluster
  gather_facts: false

  tasks:
    - name: 🚀 Install kube-prometheus-stack (Helm)
      community.kubernetes.helm:
        name: kube-prom-stack
        chart_repo_url: https://prometheus-community.github.io/helm-charts
        chart_ref: kube-prometheus-stack
        chart_version: "57.0.1"
        release_namespace: monitoring
        create_namespace: true
        values:
          grafana:
            adminPassword: prom-operator

    - name: 📊 Import Grafana datasources & dashboards
      ansible.builtin.include_role:
        name: grafana

    - name: 🔔 Create Prometheus alert rules
      ansible.builtin.include_role:
        name: prometheus_alerts
