name: Deploy‑to‑EKS

on:
  workflow_run:
    workflows: [ "CI - DevOpsTrack" ]   # nom déclaré dans ci.yml
    types: [ completed ]
    branches: [ master ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-3
      CLUSTER_NAME: devopstrack-eks

    permissions:
      contents: read
      id-token: write    # OIDC vers AWS

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::245040174852:role/gha-eks-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Apply manifest
        run: kubectl apply -f deploy/k8s/base/all-in-one.yaml

      - name: Verify rollout
        run: kubectl -n devopstrack get deploy -o wide
